// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	storage "server/internal/storage"
)

// ReviewsSaver is an autogenerated mock type for the ReviewsSaver type
type ReviewsSaver struct {
	mock.Mock
}

// SaveRewiev provides a mock function with given fields: r
func (_m *ReviewsSaver) SaveRewiev(r storage.Review) error {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for SaveRewiev")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(storage.Review) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReviewsSaver creates a new instance of ReviewsSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewsSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewsSaver {
	mock := &ReviewsSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
